In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('full_dataset.csv')

In [3]:
df.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,48.0,2,492,2,16,4.0,1,1,1557,3,...,80,1,18,2,3,8,7,7,7,0
1,50.0,2,1322,1,28,3.0,1,1,1317,4,...,80,0,25,2,3,3,2,1,2,0
2,38.0,2,1495,1,4,2.0,3,1,1687,4,...,80,1,7,5,2,0,0,0,0,0
3,30.0,1,600,0,8,3.0,0,1,1747,3,...,80,1,6,0,2,4,2,1,2,1
4,36.0,1,541,2,3,4.0,3,1,481,1,...,80,1,16,2,3,13,9,1,12,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       473 non-null    float64
 1   BusinessTravel            474 non-null    int64
 2   DailyRate                 474 non-null    int64
 3   Department                474 non-null    int64
 4   DistanceFromHome          474 non-null    int64
 5   Education                 472 non-null    float64
 6   EducationField            474 non-null    int64
 7   EmployeeCount             474 non-null    int64
 8   EmployeeNumber            474 non-null    int64
 9   EnvironmentSatisfaction   474 non-null    int64
 10  Gender                    474 non-null    int64
 11  HourlyRate                474 non-null    int64
 12  JobInvolvement            474 non-null    int64
 13  JobLevel                  474 non-null    int64
 14  JobRole                   474 non-null    int64
 15  JobSatisfaction           474 non-null    int64
 16  MaritalStatus             474 non-null    int64
 17  MonthlyIncome             474 non-null    int64
 18  MonthlyRate               474 non-null    int64
 19  NumCompaniesWorked        474 non-null    int64
 20  Over18                    474 non-null    int64
 21  OverTime                  474 non-null    int64
 22  PercentSalaryHike         474 non-null    int64
 23  PerformanceRating         474 non-null    int64
 24  RelationshipSatisfaction  474 non-null    int64
 25  StandardHours             474 non-null    int64
 26  StockOptionLevel          474 non-null    int64
 27  TotalWorkingYears         474 non-null    int64
 28  TrainingTimesLastYear     474 non-null    int64
 29  WorkLifeBalance           474 non-null    int64
 30  YearsAtCompany            474 non-null    int64
 31  YearsInCurrentRole        474 non-null    int64
 32  YearsSinceLastPromotion   474 non-null    int64
 33  YearsWithCurrManager      474 non-null    int64
 34  Attrition                 474 non-null    int64
dtypes: float64(2), int64(33)
memory usage: 129.7 KB

In [6]:
df.isna().sum().sort_values(ascending=False)

Education                   2
Age                         1
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
Attrition                   0
dtype: int64

In [8]:
categoric_var=[]
numeric_var=[]
for i in df.columns:
    x = df[i].value_counts().count()
    if x < 10:
        categoric_var.append(i)
    else:
        numeric_var.append(i)

In [9]:
categoric_var

['BusinessTravel',
 'Department',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EnvironmentSatisfaction',
 'Gender',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'Over18',
 'OverTime',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'StockOptionLevel',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'Attrition']

In [10]:
numeric_var

['Age',
 'DailyRate',
 'DistanceFromHome',
 'EmployeeNumber',
 'HourlyRate',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'TotalWorkingYears',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [13]:
columnsToDrop = ["EmployeeCount",
"EmployeeNumber",
"Over18",
"StandardHours"]

In [14]:
df.columns

Index(['Age', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition'],
      dtype='object')

In [15]:
df.drop(columnsToDrop,axis=1,inplace=True)

In [16]:
df.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,48.0,2,492,2,16,4.0,1,3,0,96,...,3,1,18,2,3,8,7,7,7,0
1,50.0,2,1322,1,28,3.0,1,4,0,43,...,2,0,25,2,3,3,2,1,2,0
2,38.0,2,1495,1,4,2.0,3,4,0,87,...,4,1,7,5,2,0,0,0,0,0
3,30.0,1,600,0,8,3.0,0,3,0,66,...,3,1,6,0,2,4,2,1,2,1
4,36.0,1,541,2,3,4.0,3,1,1,48,...,1,1,16,2,3,13,9,1,12,0

In [17]:
categoric_var=[]
numeric_var=[]
for i in df.columns:
    x = df[i].value_counts().count()
    if x < 10:
        categoric_var.append(i)
    else:
        numeric_var.append(i)