In [213]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [214]:
df = pd.read_csv('full_dataset.csv')

In [215]:
df.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,48.0,2,492,2,16,4.0,1,1,1557,3,...,80,1,18,2,3,8,7,7,7,0
1,50.0,2,1322,1,28,3.0,1,1,1317,4,...,80,0,25,2,3,3,2,1,2,0
2,38.0,2,1495,1,4,2.0,3,1,1687,4,...,80,1,7,5,2,0,0,0,0,0
3,30.0,1,600,0,8,3.0,0,1,1747,3,...,80,1,6,0,2,4,2,1,2,1
4,36.0,1,541,2,3,4.0,3,1,481,1,...,80,1,16,2,3,13,9,1,12,0

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       473 non-null    float64
 1   BusinessTravel            474 non-null    int64
 2   DailyRate                 474 non-null    int64
 3   Department                474 non-null    int64
 4   DistanceFromHome          474 non-null    int64
 5   Education                 472 non-null    float64
 6   EducationField            474 non-null    int64
 7   EmployeeCount             474 non-null    int64
 8   EmployeeNumber            474 non-null    int64
 9   EnvironmentSatisfaction   474 non-null    int64
 10  Gender                    474 non-null    int64
 11  HourlyRate                474 non-null    int64
 12  JobInvolvement            474 non-null    int64
 13  JobLevel                  474 non-null    int64
 14  JobRole                   474 non-null    int64
 15  JobSatisfaction           474 non-null    int64
 16  MaritalStatus             474 non-null    int64
 17  MonthlyIncome             474 non-null    int64
 18  MonthlyRate               474 non-null    int64
 19  NumCompaniesWorked        474 non-null    int64
 20  Over18                    474 non-null    int64
 21  OverTime                  474 non-null    int64
 22  PercentSalaryHike         474 non-null    int64
 23  PerformanceRating         474 non-null    int64
 24  RelationshipSatisfaction  474 non-null    int64
 25  StandardHours             474 non-null    int64
 26  StockOptionLevel          474 non-null    int64
 27  TotalWorkingYears         474 non-null    int64
 28  TrainingTimesLastYear     474 non-null    int64
 29  WorkLifeBalance           474 non-null    int64
 30  YearsAtCompany            474 non-null    int64
 31  YearsInCurrentRole        474 non-null    int64
 32  YearsSinceLastPromotion   474 non-null    int64
 33  YearsWithCurrManager      474 non-null    int64
 34  Attrition                 474 non-null    int64
dtypes: float64(2), int64(33)
memory usage: 129.7 KB

In [217]:
categoric_var=[]
numeric_var=[]
for i in df.columns:
    x = df[i].value_counts().count()
    if x < 10:
        categoric_var.append(i)
    else:
        numeric_var.append(i)

In [218]:
categoric_var

['BusinessTravel',
 'Department',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EnvironmentSatisfaction',
 'Gender',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'Over18',
 'OverTime',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'StockOptionLevel',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'Attrition']

In [219]:
numeric_var

['Age',
 'DailyRate',
 'DistanceFromHome',
 'EmployeeNumber',
 'HourlyRate',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'TotalWorkingYears',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [220]:
columnsToDrop = ["EmployeeCount",
"EmployeeNumber",
"Over18",
"StandardHours"]

In [221]:
df.columns

Index(['Age', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition'],
      dtype='object')

In [222]:
df.drop(columnsToDrop,axis=1,inplace=True)

In [223]:
df.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,48.0,2,492,2,16,4.0,1,3,0,96,...,3,1,18,2,3,8,7,7,7,0
1,50.0,2,1322,1,28,3.0,1,4,0,43,...,2,0,25,2,3,3,2,1,2,0
2,38.0,2,1495,1,4,2.0,3,4,0,87,...,4,1,7,5,2,0,0,0,0,0
3,30.0,1,600,0,8,3.0,0,3,0,66,...,3,1,6,0,2,4,2,1,2,1
4,36.0,1,541,2,3,4.0,3,1,1,48,...,1,1,16,2,3,13,9,1,12,0

In [224]:
categoric_var=[]
numeric_var=[]
for i in df.columns:
    x = df[i].value_counts().count()
    if x < 10:
        categoric_var.append(i)
    else:
        numeric_var.append(i)

In [225]:
df.isna().sum().sort_values(ascending=False)

Education                   2
Age                         1
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
EducationField              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
Attrition                   0
dtype: int64

In [226]:
np.sum(df.isna().sum().sort_values(ascending=False)*0.01)

np.float64(0.03)

In [227]:
df[df['Education'].isna()]

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
7,47.0,0,666,1,29,NaN,1,1,1,88,...,4,1,10,2,2,10,7,9,9,1
10,48.0,2,1469,1,20,NaN,3,4,1,51,...,1,2,13,2,2,0,0,0,0,0

In [228]:
df = df.dropna()

In [229]:
df.isna().sum().sort_values(ascending=False)

Age                         0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
Attrition                   0
dtype: int64

In [230]:
df['Attrition'].value_counts()

Attrition
1    236
0    235
Name: count, dtype: int64

In [231]:
corr = df.corr(numeric_only=True)["Attrition"].sort_values(ascending=False)

In [232]:
corr

Attrition                   1.000000
OverTime                    0.289570
MaritalStatus               0.213852
Gender                      0.105036
NumCompaniesWorked          0.102124
JobRole                     0.090601
DistanceFromHome            0.089883
Department                  0.089349
EducationField              0.045647
PerformanceRating           0.016907
MonthlyRate                 0.014278
BusinessTravel              0.011391
PercentSalaryHike          -0.003496
HourlyRate                 -0.009043
DailyRate                  -0.012325
Education                  -0.020681
TrainingTimesLastYear      -0.047493
YearsSinceLastPromotion    -0.075419
EnvironmentSatisfaction    -0.080490
WorkLifeBalance            -0.081987
JobSatisfaction            -0.084555
RelationshipSatisfaction   -0.089461
StockOptionLevel           -0.167546
Age                        -0.184953
YearsAtCompany             -0.198098
JobInvolvement             -0.224906
YearsInCurrentRole         -0.229550
TotalWorkingYears          -0.236038
MonthlyIncome              -0.242156
JobLevel                   -0.249223
YearsWithCurrManager       -0.257155
Name: Attrition, dtype: float64

In [233]:
LowCorrCols = [ "DailyRate", "DistanceFromHome","HourlyRate", "MonthlyRate", "NumCompaniesWorked", "PercentSalaryHike","YearsSinceLastPromotion"]

In [234]:
df.drop(LowCorrCols,axis=1,inplace=True)

In [235]:
df.head()

,Age,BusinessTravel,Department,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsWithCurrManager,Attrition
0,48.0,2,2,4.0,1,3,0,3,2,7,...,3,3,1,18,2,3,8,7,7,0
1,50.0,2,1,3.0,1,4,0,3,4,5,...,3,2,0,25,2,3,3,2,2,0
2,38.0,2,1,2.0,3,4,0,3,1,2,...,3,4,1,7,5,2,0,0,0,0
3,30.0,1,0,3.0,0,3,0,2,1,1,...,3,3,1,6,0,2,4,2,2,1
4,36.0,1,2,4.0,3,1,1,2,3,7,...,3,1,1,16,2,3,13,9,12,0

In [236]:
from sklearn.preprocessing import StandardScaler

In [237]:
scaler = StandardScaler()

In [238]:
numeric_var = [col for col in numeric_var if col not in LowCorrCols]

In [239]:
numeric_var

['Age',
 'MonthlyIncome',
 'TotalWorkingYears',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsWithCurrManager']